name: deploy

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '3.1.201'
  NODE_VERSION: '12.16.3'
  AZURE_WEBAPP_NAME: 'realworld-demo-blog'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: dotnet build and publish
        run: |
          dotnet run -p build/build.csproj

      - name: GitHub Deployment
        uses: chrnorm/deployment-action@releases/v1
        id: deployment
        with:
          token: "${{ github.token }}"
          target_url: "https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
          environment: demo
  
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/publish'

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: "https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
  
      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: "https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
